#!/usr/bin/env python3

from argparse import ArgumentParser
from modules.app import NCLIApplication


if __name__=='__main__':
    parser=ArgumentParser()
    parser.add_argument("-c", "--config")
    args=parser.parse_args()
    app=NCLIApplication(cfg=args)
    app.start